author: "Tobe O <thosakwe@gmail.com>"
description: "Dart ESTree FACADE."
environment:
  sdk: ">=1.19.0"
homepage: "https://github.com/thosakwe/estree_facade.git"
name: "estree_facade"
version: "1.0.0"
dependencies: 
  js: "^0.6.1"
